---
title: "MS211_PC1_RA204244"
output: pdf_notebook
---

```{r}
install.packages("pracma")
library(pracma)
library(ggplot2)
library(gridExtra)
```


```{r Exercicio 1}
a <- 0
b <- 0.11
for(i in 1:30000){
  a <- a + b
}
print(a,digits = 20)
```

```{r Exercicio 2,Newton-Raphson}
f <- function(x) x^3-9*x+3

df <- function(x) 3*x^2-9

x <- 0.5
e1 <- e2 <- 1 * 10^-4
i <- 1
x_vector <- c(x)

newton <- function(x,e1,e2){
  xk <- x - f(x)/df(x)
  x_vector <<- c(x_vector,xk)
  while(abs(f(xk))>=e1 & abs(xk-x)/abs(xk)>=e2){
    i <- i + 1
    x <- xk
    xk <- x - f(x)/df(x)
    x_vector <<- c(x_vector,xk)
    
  }
  resultado <- c(xk,f(xk),i)
  return(resultado)
}
newton(x,e1,e2)
```

```{r}
data <- data.frame(
  x_vector = x_vector,
  fx_vector = f(x_vector),
  dfx_vector = df(x_vector)
)

plot <- ggplot(data, aes(x = x_vector, y = fx_vector)) +
  geom_segment(aes(xend = x_vector + 0.5, yend = fx_vector + dfx_vector * 0.5), color = "red") +  # Plot tangent lines
  geom_segment(aes(xend = x_vector - 0.5, yend = fx_vector - dfx_vector * 0.5), color = "red") +  # Plot tangent lines
  geom_point(color = "blue") +  # Plot points for f(x)
  labs(x = "x", y = "f(x)") +  # Add axis labels
  theme_minimal()+# Set a minimal theme
  geom_function(fun=f,color = "green", size = 0.5)+
  xlim(-10,10)+
  geom_hline(yintercept = 0, color = "black", size = 1)  # Add a black horizontal line at y = 0

plot
```

```{r Exercicio 2,Secante}
f <- function(x) x^3-9*x+3

x0 <-0
x1 <-1
x_vector <- c(x0,x1)
e1 <- e2 <- 5 * 10^-4
i <- 0

secante <- function(x0,x1,e1,e2){
  while(abs(f(x1))>=e1 & abs(x1-x0)/abs(x1)>=e2){
    i <- i + 1
    xt <- x1 - f(x1)*(x1-x0)/(f(x1) - f(x0))
    x_vector <<- c(x_vector,xt)
    x0 <- x1
    x1 <- xt
  }
  resposta <- c(x1,f(x1),i)
  return(resposta)
}

secante(x0,x1,e1,e2)
```

```{r}
data <- data.frame(
  x_vector = x_vector,
  fx_vector = f(x_vector)
)

plot <-
  ggplot(data, aes(x = x_vector, y = fx_vector)) +
  geom_point(color = "blue") +  # Plot points
  geom_line(color = "blue",size = 1) +# Connect points with lines
  geom_text(aes(label = seq_along(x_vector)-1), vjust = -0.5, hjust = 0.5, size = 3) +
  geom_segment(aes(xend = lag(x_vector), yend = lag(fx_vector)), color = "red") +  # Plot secant lines
  labs(x = "x", y = "f(x)") +  # Labels and title
  theme_minimal()+# Set a minimal theme
  geom_function(fun=f,color = "green", size = 0.5)+
  geom_hline(yintercept = 0, color = "black", size = 1)+
  xlim(-0.5,3.5)# Add a black horizontal line at y = 0

options(repr.plot.width = 18, repr.plot.height = 16)

plot
```

```{r Exercicio 3, Eliminação de Gauss}

sistema <- t(cbind(c(2,2,1,1,7),c(1,-1,2,-1,1),c(3,2,-3,-2,4),c(4,3,2,1,12)))

vetor_solu <- function(sistema){
  for (i in 1:length(sistema[,1])){
    sistema[i,] <- sistema[i,]*(1/sistema[i,i])
  }
  for (k in length(sistema[,1]):1){
    for (j in 1:length(sistema[,1])){
      if( j != k){
        sistema[j,] <- sistema[j,]-sistema[k,]*sistema[j,k]
      }
    }
  }
  return(sistema[,ncol(sistema)])
}

Eliminacao_Gaus <- function(sistema){
  for(i in 1:(length(sistema[,1])-1)){
    if(sistema[i,i] == 0){
      break
    }
    for(j in 1:(length(sistema[,1])-i)){
      sistema[i+j,] <- sistema[i+j,] - sistema[i,]*sistema[i+j,i]/sistema[i,i]
    }
  }
  print(vetor_solu(sistema))
}


criar_b <- function(n){
  b <- numeric(n)
  for (i in 1:n){
    soma <- 0
    for(j in 1:n){
      soma <- soma + 1/(i+j-1)
    }
    b[i] <- soma
  } 
  return(cbind(hilb(n),b))
}

```


